USE CryptoNews
USE CryptoNews;
use CryptoNews;
show tables;
describe Value;
select * from Value;
select * from cryptonews;
select content from cryptonews; 
describe Value;
select currency name from Value;
select currency_name from Value;
select count(DISTINCT currency_name) from Value;
select DISTINCT currency_name from Value;
select DISTINCT content from cryptonews;
select count(DISTINCT content) from cryptonews;
select count(*) from cryptonews where content like '%bitcoin%'; 
select count(*) from cryptonews where content like '%BITCOIN%';
select * from cryptonews where content like any '%{select DISTINCT currency_name from Value}%';
select * from cryptonews where content = any (select DISTINCT currency_name from Value);
select DISTINCT currency_name from Value;
describe Value;
select * from Value where contains(currency_name, "Bitcoin");
select DISTINCT currency_name from Value;
select * from Value where currency_name like '%Bitcoin%';
select c.content from cryptonews c;
select c.content from cryptonews c join Value V on V.currency_name like '%bitcoin%'; 
select count(c.content) from cryptonews c join Value V on V.currency_name;
select count(DISTINCT c.content) from cryptonews c join Value V on V.currency_name;
select distinct currency_name from Value;
select count(DISTINCT c.content) from cryptonews c join Value V on V.currency_name like '%Ace%';
select count(DISTINCT content) from cryptonews;
select count(DISTINCT c.content) from cryptonews c inner join Value V on V.currency_name like '%Ace%';
select count(*) from cryptonews where content like '%crypto%';
select * from cryptonews where content like '%ace%';
use CryptoNews;
show tables;
select * from Value;
select count(*) from Value;
select count(distinct currency_name) from Value;
select count(c.content) from cryptonews c join Value V on V.currency_name like '%bitcoin%';
select count(DISTINCT c.content) from cryptonews c inner join Value V on V.currency_name like '%Ace%';
select count(*) from cryptonews where content like '%crypto%';
select count(distinct c.content) from cryptonews c inner join Value V on V.currency_name like '%bitcoin%';
describe cryptonews;
select count(distinct date) from cryptonews;
select distinct date from cryptonews where date like '%2018-02-18 21:%';
select count(distinct c.content) from cryptonews c where c.date like '%2018-02-18 21:%' and c.content like '%bitcoin%';
select count(distinct currency_name) from Value;
select count(distinct content) from cryptonews where date like '%2018-02-18 21:%';
select c.content from cryptonews c inner join Value V on c.content like concat('%', V.currency_name, '%') and c.date like '%2018-02-18 21:%';
select count(distinct c.content) from cryptonews c where c.date like '%2018-02-18 21:%' and c.content like '%bitcoin%';
select c.content, V.currency_name from cryptonews c inner join Value V on c.content like concat('%', V.currency_name, '%') and c.date like '%2018-02-18 21:%';
select V.currency_name, c.date, c.content from cryptonews c inner join Value V on c.content like concat('%', V.currency_name, '%') and c.date like '%2018-02-18 21:%';
use CryptoNews;
select V.currency_name, count(c.content) from cryptonews c inner join Value V on c.content like concat('%', V.currency_name, '%') and c.date like '%2018-02-20%';
SELECT link, SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(link, '/', 3), '://', -1), '/', 1), '?', 1),'www.',-2) as domain from cryptonews;
USE CryptoNews;
SELECT link, count(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(link, '/', 3), '://', -1), '/', 1), '?', 1),'www.',-2)) as domain from cryptonews;
SELECT link, count(distinct(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(link, '/', 3), '://', -1), '/', 1), '?', 1),'www.',-2))) as domain from cryptonews where content like '%bitcoin%' order by domain;
select * from currency_news;
select currency_name, count(inContent) as frequency from currency_news where date like '%2018-03-05%' and inContent = 'Y' group by currency_name order by frequency desc; 
select currency_name, count(inContent) as frequency from currency_news where date like '%2018-03-05%' and inContent = 'Y' and inTitle = 'Y' group by currency_name order by frequency desc; 
select count(distinct(currency_name)) from Value;
select count(distinct(currency_name)) from currency_news;
select * from Value;
select * from cryptonews;
select v.currency_name,count(c.content) as frequency from cryptonews c inner join Value v on c.content like concat('%', v.currency_name, '%') and c.date like '%2018-02-19 00:%' group by v.currency_name order by frequency desc;
select v.currency_name,count(c.content) as frequency from cryptonews c inner join Value v on c.content like concat('%', v.currency_name, '%') and c.date like '%2018-02-19 00:01%' group by v.currency_name order by frequency desc;
select v.currency_name,count(c.content) as frequency from cryptonews c inner join Value v on c.content like concat('%', v.currency_name, '%') and c.date like '%2018-02-19 00:%' group by v.currency_name order by frequency desc;
select max(date(date)) from cryptonews;
select c.date, v.currency_name, count(c.content) as frequency from cryptonews c inner join Value v on c.content like concat('% ', v.currency_name, ' %') and c.date like concat('%', (select max(date(date)) from cryptonews), '%') group by v.currency_name order by frequency desc;
select distinct(v.currency_name), count(c.content) as frequency from cryptonews c left join Value v on c.content like concat('% ', (select distinct(currency_name) from Value as va where va.currency_name = v.currency_name), ' %') and c.date like '%2018-03-14%' group by v.currency_name order by frequency desc;
select distinct(date(date)) from cryptonews;
select count(*) from cryptonews where date like '%2018-02-19%';
SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(link, '/', 3), '://', -1), '/', 1), '?', 1),'www.',-2) as domain, count(link) as freq from cryptonews where content like '%bitcoin%' group by domain order by freq desc;
select date(time) as t, quote from Value where currency_name='Bitcoin' group by t order by t;